Replaced datetime.now().timestamp() with time.time()
stefanluth/ts3python pull request #28
Opened 2022-02-05 05:32 UTC by Minkowski104

2022-02-05 07:49 UTC, stefanluth reviewed
Hi, thank you for your help! There are two more occurrences of `datetime.now().timestamp()` in `time_tracker.py`. You should then be able to remove the datetime import within that file.

2022-02-05 17:45 UTC, stefanluth requested changes

2022-02-05 17:45 UTC, stefanluth commented on modules/time_tracker/ProfilesDB.py
>  from datetime import datetime
```suggestion
```
This import can be removed as well.

2022-02-05 17:49 UTC, stefanluth commented
Please create a new branch for this pull request. If you need help on how to do that, just let me know :) A few guidelines can be found [here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) and [here](https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches).

2022-02-06 03:06 UTC, Minkowski104 commented
> Please create a new branch for this pull request. If you need help on how to do that, just let me know :) A few guidelines can be found [here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) and [here](https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches).

I have create a new branch by the name b1 for the pull request. #29  I hope I have done it right finally. I really appreciate your guidance. Please let me know if I have done it right this time.

2022-02-06 14:42 UTC, stefanluth commented
> I have create a new branch by the name b1 for the pull request. #29 I hope I have done it right finally. I really appreciate your guidance. Please let me know if I have done it right this time.

Looks good! I'll continue our conversation over there :)

2022-02-06 14:42 UTC, closed without merging